on: [push, pull_request]
name: build and create release
jobs:
  build:
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            go-version: 1.21.x
            artifact_name: go-rest-api
            asset_name: go-rest-api-linux
          - os: macos-latest
            go-version: 1.21.x
            artifact_name: go-rest-api
            asset_name: onygo-rest-apidev-macos
          - os: windows-latest
            go-version: 1.21.x
            artifact_name: go-rest-api.exe
            asset_name: go-rest-api-windows.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: go build .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
